# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "requests>=2.31.0",
# ]
# ///

"""
Example script generated by Vibescriptor.

This demonstrates the format of scripts that Vibescriptor creates:
- UV inline metadata for dependency management
- Clear documentation
- Error handling
- Educational comments

Purpose: Download a file from a URL with progress tracking
Usage: uv run example_generated_script.py
"""

import sys
from pathlib import Path
from urllib.parse import urlparse

import requests


def download_file(url: str, output_path: Path) -> bool:
    """
    Download a file from a URL with progress tracking.

    Args:
        url: The URL to download from
        output_path: Where to save the file

    Returns:
        True if successful, False otherwise
    """
    try:
        # Send GET request with streaming enabled
        # This allows us to download large files without loading everything into memory
        response = requests.get(url, stream=True, timeout=30)
        response.raise_for_status()

        # Get total file size from headers
        total_size = int(response.headers.get('content-length', 0))

        # Create parent directories if they don't exist
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Download and write file in chunks
        downloaded = 0
        chunk_size = 8192  # 8KB chunks

        print(f"Downloading {url}...")
        print(f"Saving to: {output_path}")

        with open(output_path, 'wb') as file:
            for chunk in response.iter_content(chunk_size=chunk_size):
                if chunk:  # Filter out keep-alive chunks
                    file.write(chunk)
                    downloaded += len(chunk)

                    # Show progress if we know the total size
                    if total_size > 0:
                        percent = (downloaded / total_size) * 100
                        print(f"\rProgress: {percent:.1f}%", end='', flush=True)

        print("\n✓ Download complete!")
        return True

    except requests.exceptions.RequestException as e:
        print(f"\n✗ Error downloading file: {e}")
        return False
    except IOError as e:
        print(f"\n✗ Error saving file: {e}")
        return False


def main():
    """Main function to demonstrate script usage."""
    # Example URL (replace with actual URL)
    url = "https://example.com/file.pdf"

    # Parse filename from URL or use default
    parsed_url = urlparse(url)
    filename = Path(parsed_url.path).name or "downloaded_file"

    # Save to current directory
    output_path = Path.cwd() / filename

    # Perform download
    success = download_file(url, output_path)

    # Exit with appropriate status code
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
